import type { FunderCriteria } from './funderScore'

export const HARBOR_ADVANCE_CRITERIA: FunderCriteria = {
  industries: ['auto repair', 'restaurants'],
  excludedIndustries: ['cannabis', 'adult'],
  preferredIndustries: ['auto repair'],
  states: ['TX', 'FL', 'AZ'],
  minAvgMonthlyRevenue: 40000,
  maxAvgMonthlyRevenue: 400000,
  minTimeInBusinessMonths: 6,
  maxPosition: 2,
  minRequestedAmount: 10000,
  maxRequestedAmount: 250000,
  maxNsfCount: 6,
  maxNegativeDays: 8,
  maxExistingPositions: 2,
  minDepositCount: 12,
  minAvgDailyBalance: 4000,
  allowStacking: true,
  weekendDepositsOk: true,
  entityTypes: ['llc', 'corp', 'inc'],
  excludedSic: ['7299'],
  maxHoldbackPct: 25,
  minCreditScore: 500,
  bankruptcyOk: true,
  useOfFunds: ['working capital', 'expansion', 'equipment'],
  maxTimeToFundDays: 14,
}

export const NORTHSTAR_CAPITAL_CRITERIA: FunderCriteria = {
  industries: ['auto repair', 'restaurants'],
  excludedIndustries: ['cannabis', 'crypto', 'adult'],
  preferredIndustries: ['restaurants'],
  states: ['TX', 'FL'],
  minAvgMonthlyRevenue: 50000,
  maxAvgMonthlyRevenue: 300000,
  minTimeInBusinessMonths: 12,
  maxPosition: 1,
  minRequestedAmount: 20000,
  maxRequestedAmount: 150000,
  maxNsfCount: 3,
  maxNegativeDays: 4,
  maxExistingPositions: 1,
  minDepositCount: 18,
  minAvgDailyBalance: 8000,
  allowStacking: false,
  weekendDepositsOk: false,
  entityTypes: ['llc', 'corp'],
  excludedSic: ['7299', '7993'],
  maxHoldbackPct: 20,
  minCreditScore: 580,
  bankruptcyOk: false,
  useOfFunds: ['working capital', 'expansion'],
  maxTimeToFundDays: 10,
}

export const SEEDED_FUNDER_CRITERIA: Record<string, FunderCriteria> = {
  harbor: HARBOR_ADVANCE_CRITERIA,
  northstar: NORTHSTAR_CAPITAL_CRITERIA,
}
